### PR TITLE
V10

### PR DESCRIPTION
**Pull request by skttl**
Updated the package for v10. Had to change the SQL a little bit, to make it SQLite compatible...

### CODE REVIEW

**Comment by DanDiplo** [comment]
Oh, man, that is really great, but I was also working on this myself in the v10 branch! I think I made the exact same changes you have. We must literally have been both working on it at the same time! In fact, I just added a NuGet release for v10 - https://www.nuget.org/packages/Diplo.GodMode/

Are your changes compatible with v9 too? I didn't really want to go down the multi-targeting route so I've just taken the "simple" way of having a separate v10 branch for Umbraco 10. 

I could do with some advice on best way to potentially support both...

Anyway, I do really appreciate you helping out. If you can see any improvements that can be merged into the v10 branch that you have made, please do make a new PR for those.

**Comment by skttl** [comment]
I didn't even notice that! Don't sweat it, I didn't spend much time on it :)

I don't think it's v9 compatible because of namespace changes. If I were you, I would just end v9 support from this.

I was thinking of changing it into a Razor Class Library, I might do that later :)

**Comment by DanDiplo** [comment]
@skttl You probably didn't notice because I've literally only pushed it! We really were on at the same time. But I do appreciate your help and definitely interested in the Razor Class Library thing (I read Kevin's post).

I agree, I'll probably end support for v9 unless there's something I need myself. But if you have any ideas for anything new for v10, I'd be interested. I'm kinda running out of new ideas. I would love to work out a way to dig into Block Editor components to work out dependencies, but there doesn't seem anyway with the way Umbraco stores this data just as JSON blobs. But any ideas welcome!

**Comment by DanDiplo** [comment]
So I'll close this for now, but please know I really appreciate your efforts. You've helped me loads with this project!

**Pull request closed without merging**
